### ISSUE TITLE
setup.py automated installation

### ISSUE THREAD

**Issue by hlasimpk** [rigdenlab/SIMBAD#5] opened 2017-02-14 21:00 UTC
```
Cannot find configuration file: /Applications/ccp4-7.0/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/simbad-0.0.1-py2.7.egg/simbad/static/simbad.ini - terminating...

**********************************************************************
*******************          SIMBAD ERROR          *******************
**********************************************************************

Error running main SIMBAD program: Cannot find configuration file: /Applications/ccp4-7.0/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/simbad-0.0.1-py2.7.egg/simbad/static/simbad.ini - terminating...

**********************************************************************
```

**Comment by fsimkovic** [comment] 2017-02-14 21:10
What is the command you run to reproduce this? Did you use 'ccp4-python setup.py develop' or 'install'?

**Comment by hlasimpk** [comment] 2017-02-14 21:20
I used 'ccp4-python setup.py install' (I wasn't aware there was a develop)

Could this have caused the issue?

**Comment by hlasimpk** [comment] 2017-02-14 21:25
So I've run it with the develop flag and it worked fine, out of curiosity, why doesn't install do that?

**Comment by fsimkovic** [comment] 2017-02-14 21:30
Interesting, 'develop' puts only a symlink into the site-packages directory whereas install moves the files physically to that directory. I will have a look into this tomorrow morning. 

Check the README file, I've written it all out there how to do the different installs.

**Comment by fsimkovic** [comment] 2017-02-14 22:18
Could you try the following?

```bash
ccp4-python -m pip uninstall simbad
ccp4-python setup.py install
simbad <MTZ>
```
Maybe re-installing it resolves the issue.

**Comment by hlasimpk** [comment] 2017-02-14 22:36
Tried it, same result as before. When I look in /Applications/ccp4-7.0/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/simbad-0.0.1-py2.7.egg/simbad/

I can see util and parsers but not static, as if the file is not being copied across.

**Comment by fsimkovic** [comment] 2017-02-15 09:08
There seems to be an issue on OS X that puts the `simbad` script not in the `$CCP4/bin` directory but instead to `$CCP4/Frameworks/Python.framework/Versions/2.7/bin`. The executable is not picked up and I'm not entirely sure which simbad script you are executing but not the right now.

The solution is to use the following command during installation
```bash
ccp4-python setup.py install --install-scripts $CCP4/bin --force
```
The ``--force`` re-installs everything, maybe only essential the first time you install it.

**Comment by hlasimpk** [comment] 2017-02-15 09:48
I'll test this out this afternoon and report back, if it works we should add that to the documentation

**Comment by hlasimpk** [comment] 2017-02-15 10:12
Just tested out the command 
```
ccp4-python setup.py install --install-scripts $CCP4/bin --force
```

This solved the issue with the simbad.exe being put in $CCP4/Frameworks/Python.framework/Versions/2.7/bin however this error still remains:

Error running main SIMBAD program: Cannot find configuration file: /Applications/ccp4-7.0/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/simbad-0.0.1-py2.7.egg/simbad/static/simbad.ini - terminating...

**Comment by fsimkovic** [comment] 2017-02-15 10:52
Maybe try the following:
```bash
$ cd ~/Downloads
$ rm -rf /Applications/ccp4-7.0/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/simbad-0.0.1-py2.7.egg /Applications/ccp4-7.0/bin/simbad
$ git clone https://github.com/rigdenlab/SIMBAD.git
$ cd SIMBAD
$ ccp4-python setup.py install --install-scripts > log 2>&1 &
$ simbad -mtz <MTZ FILE>
```
Let me know how that goes. If it fails, post the contents of the ``log`` file.

**Comment by hlasimpk** [comment] 2017-02-15 13:14
I've tried your last suggestion on the setup bug. Still no solution but I can give you some extra information. 

When I follow your instructions, i.e. I delete the egg files, download a new clone of SIMBAD, do setup.py install etc.. and run SIMBAD in the SIMBAD directory, the simbad.ini file in the simbad/static dir is found (note that the static dir is not copied to the egg directory in ccp4). 
This then crashes when I try to run SIMBAD with the attached debug log. 

[debug.txt](https://github.com/rigdenlab/SIMBAD/files/777124/debug.txt)

It looks like the pickle file containing the PDB information cannot be found/read. 

I also tried running this outside of the SIMBAD directory which results in the same crash I was getting before.

**Comment by fsimkovic** [comment] 2017-02-15 13:19
Please post the log file from your installation. That's much more informative about what's going on here.

**Comment by hlasimpk** [comment] 2017-02-15 13:25
[SIMBAD.log](https://github.com/rigdenlab/SIMBAD/files/777148/SIMBAD.txt)?

**Comment by fsimkovic** [comment] 2017-02-15 13:27
The log from this command
```bash
$ ccp4-python setup.py install --install-scripts $CCP4/bin > log 2>&1
```

**Comment by hlasimpk** [comment] 2017-02-15 13:30
Oh, my bad. Here is that [log(https://github.com/rigdenlab/SIMBAD/files/777161/log.txt)

**Comment by fsimkovic** [comment] 2017-02-15 13:42
Okay, remove all files in your CCP4 installation
```bash
$ find $CCP4 -name simbad* | xargs rm -rf
$ cd ~/Downloads
$ git clone https://github.com/rigdenlab/SIMBAD.git && cd SIMBAD
$ ccp4-python setup.py install --prefix $CCP4 --install-scripts $CCP4/bin
$ cd .. && rm -rf SIMBAD
$ simbad -mtz <MTZ FILE>
```
See if this works ...

**Comment by hlasimpk** [comment] 2017-02-15 13:53
File "setup.py", line 30
    return main_ns['__version__']globals()

Is returned when I use"

```
ccp4-python setup.py install --prefix $CCP4 --install-scripts $CCP4/bin
```

**Comment by fsimkovic** [comment] 2017-02-15 13:58
Try again ... PyCharm added some rubbish to the ``setup.py`` script

**Comment by hlasimpk** [comment] 2017-02-15 14:10
Looks like that worked! I'm going to close this now

**Comment by fsimkovic** [comment] 2017-02-15 14:17
Let's sort the file structure to the following:

static ==> $CCP4/share
scripts ==> $CCP4/bin
source ==> $CCP4/lib/python2.7/site-packages

**Comment by fsimkovic** [comment] 2017-02-28 20:51
It appears as if I found a good solution to solving this entire installation problem. Changes commited to ConKit in rigdenlab/conkit@3eb47a9cf65146f0bcb50d2dcbb62f880c0d7bc6. Basic approach in **ConKit** consists of the following:

```bash
ccp4-python setup.py install \
    --install-scripts=$CCP4/bin \
    --install-lib=$CCP4/lib/py2/site-packages \
    --script-python-path=ccp4-python
```

The first two flags ``--install-scripts`` and ``--install-lib`` are basic `install` flags provided by [setuptools](https://setuptools.readthedocs.io/en/latest/). The flag `--script-python-path` is a custom flag and basically adds the `ccp4-python` binary to the generated scripts.

Any thoughts @hlasimpk? Do you think we should default these and leave the flags available for an installations outside of CCP4? Is this even possible or does SIMBAD depend too much on CCP4 dependencies?

**Comment by fsimkovic** [comment] 2017-03-05 20:47
Changes for installation commited in 2d0f0a66fb1cba14cc9814114c6297b4ae4006cb. Closing this issue as this seems the most pythonic and setuptools-like.

**Closed by fsimkovic** 2017-03-05 20:47 UTC
Labels: enhancement
